services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branches: main
  - type: web
    name: frontend
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    plan: free
    branches: main
<<<<<<< Updated upstream
=======
  
>>>>>>> Stashed changes
